routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::prefix('/admin')->name('admin.')->group(function() {

    // Rutas de Inicio de Sesión y Registro de Usuarios
    Route::get('/login', [App\Http\Controllers\Backend\LoginController::class, 'showLogin'])->name('showLogin');
    Route::post('/login', [App\Http\Controllers\Backend\LoginController::class, 'login'])->name('login');
    Route::get('/register', [App\Http\Controllers\Backend\RegisterController::class, 'showRegister'])->name('showRegister');
    Route::post('/register', [App\Http\Controllers\Backend\RegisterController::class, 'store'])->name('store');

    Route::group(['middleware' => ['auth:admin']], function () {

        // Dashboard
        Route::get('/dashboard', [App\Http\Controllers\Backend\DashboardController::class, 'dashboard'])->name('dashboard');

        // Rutas de Usuarios
        Route::get('/users', [App\Http\Controllers\Backend\UsersController::class, 'getUsers'])->name('users');
        Route::post('/saveUser', [App\Http\Controllers\Backend\UsersController::class, 'saveUser'])->name('users.store');
        Route::post('/getUser', [App\Http\Controllers\Backend\UsersController::class, 'getUser'])->name('users.show');
        Route::put('/updateUser', [App\Http\Controllers\Backend\UsersController::class, 'updateUser'])->name('users.update');
        Route::post('/deleteUser', [App\Http\Controllers\Backend\UsersController::class, 'deleteUser'])->name('users.delete');
        Route::get('/logout', [App\Http\Controllers\Backend\LoginController::class, 'logout'])->name('logout');

        // Rutas de Empresas
        Route::get('/enterprises', [App\Http\Controllers\Backend\EnterprisesController::class, 'getEnterprises'])->name('enterprises');
        Route::post('/saveEnterprise', [App\Http\Controllers\Backend\EnterprisesController::class, 'saveEnterprise'])->name('enterprises.store');
        Route::post('/getEnterprise', [App\Http\Controllers\Backend\EnterprisesController::class, 'getEnterprise'])->name('enterprises.show');
        Route::put('/updateEnterprise', [App\Http\Controllers\Backend\EnterprisesController::class, 'updateEnterprise'])->name('enterprises.update');
        Route::post('/deleteEnterprise', [App\Http\Controllers\Backend\EnterprisesController::class, 'deleteEnterprise'])->name('enterprises.delete');

        // Rutas de Categorias
        Route::get('/categories', [App\Http\Controllers\Backend\CategoriesController::class, 'getCategories'])->name('categories');
        Route::post('/saveCategory', [App\Http\Controllers\Backend\CategoriesController::class, 'saveCategory'])->name('categories.store');
        Route::post('/getCategory', [App\Http\Controllers\Backend\CategoriesController::class, 'getCategory'])->name('categories.show');
        Route::put('/updateCategory', [App\Http\Controllers\Backend\CategoriesController::class, 'updateCategory'])->name('categories.update');
        Route::post('/deleteCategory', [App\Http\Controllers\Backend\CategoriesController::class, 'deleteCategory'])->name('categories.delete');

        // Rutas de Subcategorias
        Route::get('/subcategories', [App\Http\Controllers\Backend\SubcategoriesController::class, 'getSubcategories'])->name('subcategories');
        Route::post('/saveSubcategory', [App\Http\Controllers\Backend\SubcategoriesController::class, 'saveSubcategory'])->name('subcategories.store');
        Route::post('/getSubcategory', [App\Http\Controllers\Backend\SubcategoriesController::class, 'getSubcategory'])->name('subcategories.show');
        Route::put('/updateSubcategory', [App\Http\Controllers\Backend\SubcategoriesController::class, 'updateSubcategory'])->name('subcategories.update');
        Route::post('/deleteSubcategory', [App\Http\Controllers\Backend\SubcategoriesController::class, 'deleteSubcategory'])->name('subcategories.delete');

        // Rutas de Productos
        Route::get('/products', [App\Http\Controllers\Backend\ProductsController::class, 'getProducts'])->name('products');
        Route::post('/saveProduct', [App\Http\Controllers\Backend\ProductsController::class, 'saveProduct'])->name('products.store');
        Route::post('/getProduct', [App\Http\Controllers\Backend\ProductsController::class, 'getProduct'])->name('products.show');
        Route::put('/updateProduct', [App\Http\Controllers\Backend\ProductsController::class, 'updateProduct'])->name('products.update');
        Route::post('/deleteProduct', [App\Http\Controllers\Backend\ProductsController::class, 'deleteProduct'])->name('products.delete');

        // Rutas de Contenido de Productos
        Route::get('/productContents', [App\Http\Controllers\Backend\ProductContentsController::class, 'getProductContents'])->name('productContents');
        Route::post('/saveProductContent', [App\Http\Controllers\Backend\ProductContentsController::class, 'saveProductContent'])->name('productContents.store');
        Route::post('/getProductContent', [App\Http\Controllers\Backend\ProductContentsController::class, 'getProductContent'])->name('productContents.show');
        Route::put('/updateProductContent', [App\Http\Controllers\Backend\ProductContentsController::class, 'updateProductContent'])->name('productContents.update');
        Route::post('/deleteProductContent', [App\Http\Controllers\Backend\ProductContentsController::class, 'deleteProductContent'])->name('productContents.delete');

        // Rutas de Bebidas
        Route::get('/bebidas', [App\Http\Controllers\Backend\BebidasController::class, 'getBebidas'])->name('bebidas');
        Route::post('/saveBebida', [App\Http\Controllers\Backend\BebidasController::class, 'saveBebida'])->name('bebidas.store');
        Route::post('/getBebida', [App\Http\Controllers\Backend\BebidasController::class, 'getBebida'])->name('bebidas.show');
        Route::put('/updateBebida', [App\Http\Controllers\Backend\BebidasController::class, 'updateBebida'])->name('bebidas.update');
        Route::post('/deleteBebida', [App\Http\Controllers\Backend\BebidasController::class, 'deleteBebida'])->name('bebidas.delete');

        // Rutas de Pedidos
        Route::get('/orders', [App\Http\Controllers\Backend\OrdersController::class, 'getOrders'])->name('orders');
        Route::post('/adminDownloadPDF', [App\Http\Controllers\Backend\OrdersController::class, 'adminDownloadPDF'])->name('adminDownloadPDF');

        //  Rutas de Detalles del Pedido
        Route::get('/orderDetails', [App\Http\Controllers\Backend\OrderDetailsController::class, 'getOrderDetails'])->name('orderDetails');
        Route::post('/getOrderDetail', [App\Http\Controllers\Backend\OrderDetailsController::class, 'getOrderDetail'])->name('orderDetails.show');
        Route::put('/updateOrderDetail', [App\Http\Controllers\Backend\OrderDetailsController::class, 'updateOrderDetail'])->name('orderDetails.update');
        Route::post('/deleteOrderDetail', [App\Http\Controllers\Backend\OrderDetailsController::class, 'deleteOrderDetail'])->name('orderDetails.delete');

        // Rutas de Costos de Envio
        Route::get('/shippings', [App\Http\Controllers\Backend\ShippingsController::class, 'getShippings'])->name('shippings');
        Route::post('/saveShipping', [App\Http\Controllers\Backend\ShippingsController::class, 'saveShipping'])->name('shippings.store');
        Route::post('/getShipping', [App\Http\Controllers\Backend\ShippingsController::class, 'getShipping'])->name('shippings.show');
        Route::put('/updateShipping', [App\Http\Controllers\Backend\ShippingsController::class, 'updateShipping'])->name('shippings.update');
        Route::post('/deleteShipping', [App\Http\Controllers\Backend\ShippingsController::class, 'deleteShipping'])->name('shippings.delete');

        // Rutas de Codigos Postales
        Route::get('/postalCodes', [App\Http\Controllers\Backend\PostalCodesController::class, 'getPostalCodes'])->name('postalCodes');
        Route::post('/savePostalCode', [App\Http\Controllers\Backend\PostalCodesController::class, 'savePostalCode'])->name('postalCodes.store');
        Route::post('/getPostalCode', [App\Http\Controllers\Backend\PostalCodesController::class, 'getPostalCode'])->name('postalCodes.show');
        Route::put('/updatePostalCode', [App\Http\Controllers\Backend\PostalCodesController::class, 'updatePostalCode'])->name('postalCodes.update');
        Route::post('/deletePostalCode', [App\Http\Controllers\Backend\PostalCodesController::class, 'deletePostalCode'])->name('postalCodes.delete');

        // Rutas de Formas de Pago
        Route::get('/payments', [App\Http\Controllers\Backend\PaymentsController::class, 'getPayments'])->name('payments');
        Route::post('/savePayment', [App\Http\Controllers\Backend\PaymentsController::class, 'savePayment'])->name('payments.store');
        Route::post('/getPayment', [App\Http\Controllers\Backend\PaymentsController::class, 'getPayment'])->name('payments.show');
        Route::put('/updatePayment', [App\Http\Controllers\Backend\PaymentsController::class, 'updatePayment'])->name('payments.update');
        Route::post('/deletePayment', [App\Http\Controllers\Backend\PaymentsController::class, 'deletePayment'])->name('payments.delete');
    });
});

Route::prefix('/')->group(function (){
    Route::get('/', [App\Http\Controllers\Frontend\WelcomeController::class, 'welcome'])->name('welcome');

    //Rutas de Productos
    Route::get('/especialidades', [App\Http\Controllers\Frontend\EspecialidadesController::class, 'getEspecialidades'])->name('getEspecialidades');

app/Http/Controllers/Backend/BebidasController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\Bebida;
use App\Models\ProductContent;
use App\Models\Subcategory;
use App\Models\Product;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use File;

class BebidasController extends Controller
{
    public function getBebidas()
    {
        $bebidas = DB::table('products')
            ->join('subcategories', 'subcategories.id', '=', 'products.subcategory_id')
            ->join('categories', 'categories.id', '=', 'subcategories.category_id')
            ->join('product_contents', 'product_contents.product_id', '=', 'products.id')
            ->where('categories.slug', '=', 'bebidas')
            ->whereIn('subcategories.slug', ['cervezas', 'refrescos', 'licores', 'cocteleria', 'micheladas'])
            ->select('products.*', 'subcategories.name as subcategory', 'product_contents.price as price')
            ->get();

        $subcate = DB::table('subcategories')
            ->join('categories', 'categories.id', '=', 'subcategories.category_id')
            ->where('categories.slug', '=', 'bebidas')
            ->select('subcategories.*')
            ->orderBy('subcategories.name', 'asc')
            ->get();
        // dd($subcate);

        return view('backend.bebidas.index', compact('bebidas', 'subcate'));
    }

    public function saveBebida(Request $request)
    {
        $newBebida = Product::where('slug', '=', $request->modal_slug)->first();

        if(is_null($newBebida)){
            if($request->hasFile('modal_image')){
                $imagen = dirname(base_path(), 1).'/public_html/backend/img/bebidas/'.$request->modal_slug.'.'.$request->modal_image->getClientOriginalExtension();
                File::delete($imagen);

                $imageName = $request->modal_slug.'.'.$request->modal_image->getClientOriginalExtension();
                $routeImage = 'backend/img/bebidas/'.$imageName;

                $bebida = new Product();
                $bebida->name = $request->modal_name;
                $bebida->slug = $request->modal_slug;
                $bebida->image = $routeImage;
                $bebida->description = $request->modal_description;
                $bebida->subcategory_id = $request->modal_subcategory_id;
                $bebida->status = 'I';

                $bebida->save();

                $request->modal_image->move(dirname(base_path(), 1).'/public_html/backend/img/bebidas/', $imageName);

                ProductContent::create([
                    'product_id' => $bebida->id,
                    'type' => 'BEBIDA',
                    'price' => $request->modal_price
                ]);

                return redirect()->back()->with('success', 'Bebida Creada Correctamente');
            }
            else{
                $routeImage = 'backend/img/logos/logo_casita.png';
                $bebida = new Product();
                $bebida->name = $request->modal_name;
                $bebida->slug = $request->modal_slug;
                $bebida->image = $routeImage;
                $bebida->description = $request->modal_description;
                $bebida->subcategory_id = $request->modal_subcategory_id;
                $bebida->status = 'I';

                $bebida->save();

                ProductContent::create([
                    'product_id' => $bebida->id,
                    'type' => 'BEBIDA',
                    'price' => $request->modal_price
                ]);

                return redirect()->back()->with('success', 'Bebida Creada Correctamente');

            }

        }
        else{
            return redirect()->back()->with('errors', 'Ya existe esa Bebida');
        }
    }

    public function getBebida(Request $request)
    {
        $bebida = DB::table('products')
            ->join('product_contents', 'product_contents.product_id', '=', 'products.id')
            ->where('products.id', '=', $request->id)
            ->select('products.*')
            ->get();
        // dd($bebida);
        return $bebida;
    }

    public function updateBebida(Request $request)
    {
        $bebida = Product::where('id', '=', $request->modal_update_id)->first();

        if(!is_null($bebida)){

            $slug = DB::table('products')
                ->where('id', '<>', $request->modal_update_id)
                ->where('slug', '=', $request->modal_update_slug)
                ->first();

            if(!$slug){
                if($request->hasFile('modal_update_image')){
                    $file = dirname(base_path(), 1).'/public_html/'.$bebida->image;
                        File::delete($file);
                        $imageName = $request->modal_update_slug.'.'.$request->modal_update_image->getClientOriginalExtension();
                        $route = 'backend/img/bebidas/'.$imageName;

                        $bebida->name = $request->modal_update_name;
                        $bebida->slug = $request->modal_update_slug;
                        $bebida->image = $route;
                        $bebida->subcategory_id = $request->modal_update_subcategory_id;
                        $bebida->status = $request->modal_update_status;
                        $bebida->description = $request->modal_update_description;
                        $bebida->update();

                        $request->modal_update_image->move(dirname(base_path(), 1).'/public_html/backend/img/bebidas/',$imageName);

                        $contenido = ProductContent::where('product_id', $bebida->id)->first();

                        $contenido->price = $request->modal_update_price;
                        $contenido->update();

                    return redirect()->back()->with('success', 'Bebida Actualizada Correctamente');
                }
                else{
                    $bebida->name = $request->modal_update_name;
                    $bebida->slug = $request->modal_update_slug;
                    $bebida->subcategory_id = $request->modal_update_subcategory_id;
                    $bebida->description = $request->modal_update_description;
                    $bebida->status = $request->modal_update_status;
                    $bebida->update();

                    $contenido = ProductContent::where('product_id', $bebida->id)->first();

                    $contenido->price = $request->modal_update_price;
                    $contenido->update();

                    return redirect()->back()->with('success', 'Bebida Actualizada Correctamente');
                }

            }
            else{
                return redirect()->back()->with('errors', 'Ya existe esa Bebida');
            }

        }
        else{
            return redirect()->back()->with('errors', 'No existe esa Bebida');
        }
    }

    public function deleteBebida(Request $request)
    {
        $logo = Product::where('id', $request->id)->select('image')->first();

        $image = dirname(base_path(), 1).'/public_html/'.$logo->image;


        File::delete($image);
        $bebida = Product::where('id', $request->id)->first();

        $bebida->delete();
    }
}

app/Http/Controllers/Backend/DashboardController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class DashboardController extends Controller
{
    public function dashboard()
    {
        return view('backend.admin.dashboard');
    }
}

app/Http/Controllers/Backend/OrderDetailsController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class OrderDetailsController extends Controller
{
    //
}

resources/views/layouts/backend/errors.blade.php
@if (count($errors) > 0)
    <div class="alert alert-danger">
        <strong>Algo salió mal</strong>

        <br><br>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

resources/views/layouts/backend/main.blade.php
<!DOCTYPE html>
<!--
This is a starter template page. Use this page to start your new project from
scratch. This page gets rid of all links and provides the needed markup only.
-->
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <link rel="apple-touch-icon" sizes="76x76" href="{{ asset('backend/img/logos/logo_casita.png') }}">
    <link rel="icon" type="image/png" href="{{ asset('backend/img/logos/logo_casita.png') }}">

    <title>CCD @yield('title')</title>

    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="{{ asset('backend/plugins/fontawesome-free/css/all.min.css') }}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{{ asset('backend/css/adminlte.min.css') }}">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
    @yield('custom-css')
</head>
<body class="hold-transition sidebar-mini">
    <div class="wrapper">

        <!-- Navbar -->
        <nav class="main-header navbar navbar-expand navbar-primary navbar-dark">
            <ul class="navbar-nav">
                <li class="nav-item">
                <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
                </li>

            </ul>
            <!-- SEARCH FORM -->
            <form class="form-inline ml-auto">
            <div class="input-group input-group-sm">
                <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
                <div class="input-group-append">
                <button class="btn btn-navbar" type="submit">
                    <i class="fas fa-search"></i>
                </button>
                </div>
            </div>
            </form>
            <ul class="navbar-nav ml-auto">
                <div class="dropdown show">
                    <a class="btn btn-transparent dropdown-toggle text-white" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown">
                        {{ Auth::user()->name }}
                    </a>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                        <a class="dropdown-item" href="#">Ver Perfil</a>
                        <a class="dropdown-item" href="{{ route('admin.logout') }}">Cerrar Sesión</a>
                    </div>
                </div>
            </ul>
        </nav>
        <!-- /.navbar -->

        <!-- Main Sidebar Container -->
        <aside class="main-sidebar sidebar-dark-primary elevation-4">
                <!-- Brand Logo -->
                <a href="{{ route('admin.dashboard') }}" class="brand-link text-center">
                    <img src="{{ asset('backend/img/logos/logo_nombre.png') }}" alt="CCD Logo" class="img-fluid " width="120" height="40">
                </a>
                <!-- Sidebar -->
                <div class="sidebar">
                    <!-- Sidebar Menu -->
                    <nav class="mt-2">
                            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                                <li class="nav-item">
                                    <a href="{{ route('admin.dashboard') }}" class="nav-link">
                                        <i class="nav-icon fas fa-tachometer-alt"></i>
                                        <p>Dashboard</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="{{ route('admin.users') }}" class="nav-link">
                                        <i class="nav-icon fas fa-user"></i>
                                        <p>Usuarios</p>
                                    </a>
                                </li>
                                <li class="nav-item has-treewview" style="background-color: rgba(23, 23, 136, 0.801); color:white">
                                    <a href="#" class="nav-link">
                                        <i class="nav-icon fas fa-building"></i>
                                        <p>
                                            Empresa
                                            <i class="right fas fa-angle-down"></i>
                                        </p>
                                    </a>
                                    <ul class="nav nav-treeview">
                                        <li class="nav-item">
                                            <a href="{{ route('admin.enterprises') }}" class="nav-link">
                                                <i class="nav-icon fas fa-info-circle"></i>
                                                <p class="text-white">Detalles de Empresa</p>
                                            </a>
                                        </li>
                                        <li class="nav-item">
                                            <a href="{{ route('admin.shippings') }}" class="nav-link">
                                                <i class="nav-icon fas fa-dollar-sign"></i>
                                                <p class="text-white">Costos de Envíos</p>
                                            </a>
                                        </li>
                                        <li class="nav-item">
                                            <a href="{{ route('admin.postalCodes') }}" class="nav-link">
                                                <i class="nav-icon fas fa-map-marked"></i>
                                                <p class="text-white">Códigos Postales</p>
                                            </a>
                                        </li>
                                        <li class="nav-item">
                                            <a href="{{ route('admin.payments') }}" class="nav-link">
                                                <i class="nav-icon fab fa-cc-visa"></i>
                                                <p class="text-white">Formas de Pago</p>
                                            </a>
                                        </li>
                                    </ul>
                                </li>
                                <li class="nav-item">
                                    <a href="{{ route('admin.categories') }}" class="nav-link">
                                        <i class="nav-icon fas fa-boxes"></i>
                                        <p>Categorías</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="{{ route('admin.subcategories') }}" class="nav-link">
                                        <i class="nav-icon fas fa-sitemap"></i>
                                        <p>Subcategorías</p>
                                    </a>
                                </li>
                                <li class="nav-item has-treewview" style="background-color: blue; color:white">
                                    <a href="#" class="nav-link">
                                        <i class="nav-icon fas fa-warehouse"></i>
                                        <p>
                                            Inventario
                                            <i class="right fas fa-angle-down"></i>
                                        </p>
                                    </a>
                                    <ul class="nav nav-treeview">
                                        <li class="nav-item">
                                            <a href="{{ route('admin.products') }}" class="nav-link">
                                                <i class="nav-icon fas fa-fish"></i>
                                                <p>Platillos</p>
                                            </a>
                                        </li>
                                        <li class="nav-item">
                                            <a href="{{ route('admin.productContents') }}" class="nav-link">
                                                <i class="nav-icon fas fa-info-circle"></i>
                                                <p>Contenido de Platillos</p>
                                            </a>
                                        </li>
                                        <li class="nav-item">
                                            <a href="{{ route('admin.bebidas') }}" class="nav-link">
                                                <i class="nav-icon fas fa-beer"></i>
                                                <p>Bebidas</p>
                                            </a>
                                        </li>
                                    </ul>
                                </li>
                                <li class="nav-item">
                                    <a href="{{ route('admin.orders') }}" class="nav-link">
                                        <i class="nav-icon fas fa-clipboard-list"></i>
                                        <p>Pedidos</p>
                                    </a>
                                </li>
                            </ul>
                    </nav>
                    <!-- /.sidebar-menu -->
                </div>
                <!-- /.sidebar -->
        </aside>

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
                <!-- Content Header (Page header) -->
                <div class="content-header">
                    <div class="container">
                        <div class="row mb-2 text-center">
                            <div class="col-sm-12">
                                <h1 class="m-0 text-dark">@yield('page-title')</h1>
                            </div><!-- /.col -->
                        </div><!-- /.row -->
                    </div><!-- /.container-fluid -->
                </div>
                <!-- /.content-header -->

                <!-- Main content -->
                <div class="content">
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-sm-12">
                                @yield('content')
                            </div>
                        </div>
                    </div><!-- /.container-fluid -->
                </div>
                <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->

        <!-- Main Footer -->
        <footer class="main-footer">
            <!-- To the right -->
            <div class="float-right d-none d-sm-inline">
            Versión 1.0.0
            </div>
            <!-- Default to the left -->
            <strong>Copyright &copy; 2021 <a href="https://www.casitadorada.com" target="blank">{{ config('app.name') }}</a>.</strong> Todos los Derechos Resevados.
        </footer>
    </div>
    <!-- ./wrapper -->

<!-- REQUIRED SCRIPTS -->

<!-- jQuery -->
<script src="{{ asset('backend/plugins/jquery/jquery.min.js') }}"></script>
<!-- Bootstrap 4 -->
<script src="{{ asset('backend/plugins/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
<!-- AdminLTE App -->
<script src="{{ asset('backend/js/adminlte.min.js') }}"></script>
@yield('custom-js')
</body>
</html>