routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::prefix('/admin')->name('admin.')->group(function() {

    // Rutas de Inicio de Sesión y Registro de Usuarios
    Route::get('/login', [App\Http\Controllers\Backend\LoginController::class, 'showLogin'])->name('showLogin');
    Route::post('/login', [App\Http\Controllers\Backend\LoginController::class, 'login'])->name('login');
    Route::get('/register', [App\Http\Controllers\Backend\RegisterController::class, 'showRegister'])->name('showRegister');
    Route::post('/register', [App\Http\Controllers\Backend\RegisterController::class, 'store'])->name('store');

    Route::group(['middleware' => ['auth:admin']], function () {

        // Dashboard
        Route::get('/dashboard', [App\Http\Controllers\Backend\DashboardController::class, 'dashboard'])->name('dashboard');

        // Rutas de Usuarios
        Route::get('/users', [App\Http\Controllers\Backend\UsersController::class, 'getUsers'])->name('users');
        Route::post('/saveUser', [App\Http\Controllers\Backend\UsersController::class, 'saveUser'])->name('users.store');
        Route::post('/getUser', [App\Http\Controllers\Backend\UsersController::class, 'getUser'])->name('users.show');
        Route::put('/updateUser', [App\Http\Controllers\Backend\UsersController::class, 'updateUser'])->name('users.update');
        Route::post('/deleteUser', [App\Http\Controllers\Backend\UsersController::class, 'deleteUser'])->name('users.delete');
        Route::get('/logout', [App\Http\Controllers\Backend\LoginController::class, 'logout'])->name('logout');

        // Rutas de Empresas
        Route::get('/enterprises', [App\Http\Controllers\Backend\EnterprisesController::class, 'getEnterprises'])->name('enterprises');
        Route::post('/saveEnterprise', [App\Http\Controllers\Backend\EnterprisesController::class, 'saveEnterprise'])->name('enterprises.store');
        Route::post('/getEnterprise', [App\Http\Controllers\Backend\EnterprisesController::class, 'getEnterprise'])->name('enterprises.show');
        Route::put('/updateEnterprise', [App\Http\Controllers\Backend\EnterprisesController::class, 'updateEnterprise'])->name('enterprises.update');
        Route::post('/deleteEnterprise', [App\Http\Controllers\Backend\EnterprisesController::class, 'deleteEnterprise'])->name('enterprises.delete');

        // Rutas de Categorias
        Route::get('/categories', [App\Http\Controllers\Backend\CategoriesController::class, 'getCategories'])->name('categories');
        Route::post('/saveCategory', [App\Http\Controllers\Backend\CategoriesController::class, 'saveCategory'])->name('categories.store');
        Route::post('/getCategory', [App\Http\Controllers\Backend\CategoriesController::class, 'getCategory'])->name('categories.show');
        Route::put('/updateCategory', [App\Http\Controllers\Backend\CategoriesController::class, 'updateCategory'])->name('categories.update');
        Route::post('/deleteCategory', [App\Http\Controllers\Backend\CategoriesController::class, 'deleteCategory'])->name('categories.delete');

        // Rutas de Subcategorias
        Route::get('/subcategories', [App\Http\Controllers\Backend\SubcategoriesController::class, 'getSubcategories'])->name('subcategories');
        Route::post('/saveSubcategory', [App\Http\Controllers\Backend\SubcategoriesController::class, 'saveSubcategory'])->name('subcategories.store');
        Route::post('/getSubcategory', [App\Http\Controllers\Backend\SubcategoriesController::class, 'getSubcategory'])->name('subcategories.show');
        Route::put('/updateSubcategory', [App\Http\Controllers\Backend\SubcategoriesController::class, 'updateSubcategory'])->name('subcategories.update');
        Route::post('/deleteSubcategory', [App\Http\Controllers\Backend\SubcategoriesController::class, 'deleteSubcategory'])->name('subcategories.delete');

        // Rutas de Productos
        Route::get('/products', [App\Http\Controllers\Backend\ProductsController::class, 'getProducts'])->name('products');
        Route::post('/saveProduct', [App\Http\Controllers\Backend\ProductsController::class, 'saveProduct'])->name('products.store');
        Route::post('/getProduct', [App\Http\Controllers\Backend\ProductsController::class, 'getProduct'])->name('products.show');
        Route::put('/updateProduct', [App\Http\Controllers\Backend\ProductsController::class, 'updateProduct'])->name('products.update');
        Route::post('/deleteProduct', [App\Http\Controllers\Backend\ProductsController::class, 'deleteProduct'])->name('products.delete');

        // Rutas de Contenido de Productos
        Route::get('/productContents', [App\Http\Controllers\Backend\ProductContentsController::class, 'getProductContents'])->name('productContents');
        Route::post('/saveProductContent', [App\Http\Controllers\Backend\ProductContentsController::class, 'saveProductContent'])->name('productContents.store');
        Route::post('/getProductContent', [App\Http\Controllers\Backend\ProductContentsController::class, 'getProductContent'])->name('productContents.show');
        Route::put('/updateProductContent', [App\Http\Controllers\Backend\ProductContentsController::class, 'updateProductContent'])->name('productContents.update');
        Route::post('/deleteProductContent', [App\Http\Controllers\Backend\ProductContentsController::class, 'deleteProductContent'])->name('productContents.delete');

        // Rutas de Bebidas
        Route::get('/bebidas', [App\Http\Controllers\Backend\BebidasController::class, 'getBebidas'])->name('bebidas');
        Route::post('/saveBebida', [App\Http\Controllers\Backend\BebidasController::class, 'saveBebida'])->name('bebidas.store');
        Route::post('/getBebida', [App\Http\Controllers\Backend\BebidasController::class, 'getBebida'])->name('bebidas.show');
        Route::put('/updateBebida', [App\Http\Controllers\Backend\BebidasController::class, 'updateBebida'])->name('bebidas.update');
        Route::post('/deleteBebida', [App\Http\Controllers\Backend\BebidasController::class, 'deleteBebida'])->name('bebidas.delete');

        // Rutas de Pedidos
        Route::get('/orders', [App\Http\Controllers\Backend\OrdersController::class, 'getOrders'])->name('orders');
        Route::post('/adminDownloadPDF', [App\Http\Controllers\Backend\OrdersController::class, 'adminDownloadPDF'])->name('adminDownloadPDF');

        //  Rutas de Detalles del Pedido
        Route::get('/orderDetails', [App\Http\Controllers\Backend\OrderDetailsController::class, 'getOrderDetails'])->name('orderDetails');
        Route::post('/getOrderDetail', [App\Http\Controllers\Backend\OrderDetailsController::class, 'getOrderDetail'])->name('orderDetails.show');
        Route::put('/updateOrderDetail', [App\Http\Controllers\Backend\OrderDetailsController::class, 'updateOrderDetail'])->name('orderDetails.update');
        Route::post('/deleteOrderDetail', [App\Http\Controllers\Backend\OrderDetailsController::class, 'deleteOrderDetail'])->name('orderDetails.delete');

        // Rutas de Costos de Envio
        Route::get('/shippings', [App\Http\Controllers\Backend\ShippingsController::class, 'getShippings'])->name('shippings');
        Route::post('/saveShipping', [App\Http\Controllers\Backend\ShippingsController::class, 'saveShipping'])->name('shippings.store');
        Route::post('/getShipping', [App\Http\Controllers\Backend\ShippingsController::class, 'getShipping'])->name('shippings.show');
        Route::put('/updateShipping', [App\Http\Controllers\Backend\ShippingsController::class, 'updateShipping'])->name('shippings.update');
        Route::post('/deleteShipping', [App\Http\Controllers\Backend\ShippingsController::class, 'deleteShipping'])->name('shippings.delete');

        // Rutas de Codigos Postales
        Route::get('/postalCodes', [App\Http\Controllers\Backend\PostalCodesController::class, 'getPostalCodes'])->name('postalCodes');
        Route::post('/savePostalCode', [App\Http\Controllers\Backend\PostalCodesController::class, 'savePostalCode'])->name('postalCodes.store');
        Route::post('/getPostalCode', [App\Http\Controllers\Backend\PostalCodesController::class, 'getPostalCode'])->name('postalCodes.show');
        Route::put('/updatePostalCode', [App\Http\Controllers\Backend\PostalCodesController::class, 'updatePostalCode'])->name('postalCodes.update');
        Route::post('/deletePostalCode', [App\Http\Controllers\Backend\PostalCodesController::class, 'deletePostalCode'])->name('postalCodes.delete');

        // Rutas de Formas de Pago
        Route::get('/payments', [App\Http\Controllers\Backend\PaymentsController::class, 'getPayments'])->name('payments');
        Route::post('/savePayment', [App\Http\Controllers\Backend\PaymentsController::class, 'savePayment'])->name('payments.store');
        Route::post('/getPayment', [App\Http\Controllers\Backend\PaymentsController::class, 'getPayment'])->name('payments.show');
        Route::put('/updatePayment', [App\Http\Controllers\Backend\PaymentsController::class, 'updatePayment'])->name('payments.update');
        Route::post('/deletePayment', [App\Http\Controllers\Backend\PaymentsController::class, 'deletePayment'])->name('payments.delete');
    });
});

Route::prefix('/')->group(function (){
    Route::get('/', [App\Http\Controllers\Frontend\WelcomeController::class, 'welcome'])->name('welcome');

    //Rutas de Productos
    Route::get('/especialidades', [App\Http\Controllers\Frontend\EspecialidadesController::class, 'getEspecialidades'])->name('getEspecialidades');

app/Http/Controllers/Backend/BebidasController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\Bebida;
use App\Models\ProductContent;
use App\Models\Subcategory;
use App\Models\Product;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use File;

class BebidasController extends Controller
{
    public function getBebidas()
    {
        $bebidas = DB::table('products')
            ->join('subcategories', 'subcategories.id', '=', 'products.subcategory_id')
            ->join('categories', 'categories.id', '=', 'subcategories.category_id')
            ->join('product_contents', 'product_contents.product_id', '=', 'products.id')
            ->where('categories.slug', '=', 'bebidas')
            ->whereIn('subcategories.slug', ['cervezas', 'refrescos', 'licores', 'cocteleria', 'micheladas'])
            ->select('products.*', 'subcategories.name as subcategory', 'product_contents.price as price')
            ->get();

        $subcate = DB::table('subcategories')
            ->join('categories', 'categories.id', '=', 'subcategories.category_id')
            ->where('categories.slug', '=', 'bebidas')
            ->select('subcategories.*')
            ->orderBy('subcategories.name', 'asc')
            ->get();
        // dd($subcate);

        return view('backend.bebidas.index', compact('bebidas', 'subcate'));
    }

    public function saveBebida(Request $request)
    {
        $newBebida = Product::where('slug', '=', $request->modal_slug)->first();

        if(is_null($newBebida)){
            if($request->hasFile('modal_image')){
                $imagen = dirname(base_path(), 1).'/public_html/backend/img/bebidas/'.$request->modal_slug.'.'.$request->modal_image->getClientOriginalExtension();
                File::delete($imagen);

                $imageName = $request->modal_slug.'.'.$request->modal_image->getClientOriginalExtension();
                $routeImage = 'backend/img/bebidas/'.$imageName;

                $bebida = new Product();
                $bebida->name = $request->modal_name;
                $bebida->slug = $request->modal_slug;
                $bebida->image = $routeImage;
                $bebida->description = $request->modal_description;
                $bebida->subcategory_id = $request->modal_subcategory_id;
                $bebida->status = 'I';

                $bebida->save();

                $request->modal_image->move(dirname(base_path(), 1).'/public_html/backend/img/bebidas/', $imageName);

                ProductContent::create([
                    'product_id' => $bebida->id,
                    'type' => 'BEBIDA',
                    'price' => $request->modal_price
                ]);

                return redirect()->back()->with('success', 'Bebida Creada Correctamente');
            }
            else{
                $routeImage = 'backend/img/logos/logo_casita.png';
                $bebida = new Product();
                $bebida->name = $request->modal_name;
                $bebida->slug = $request->modal_slug;
                $bebida->image = $routeImage;
                $bebida->description = $request->modal_description;
                $bebida->subcategory_id = $request->modal_subcategory_id;
                $bebida->status = 'I';

                $bebida->save();

                ProductContent::create([
                    'product_id' => $bebida->id,
                    'type' => 'BEBIDA',
                    'price' => $request->modal_price
                ]);

                return redirect()->back()->with('success', 'Bebida Creada Correctamente');

            }

        }
        else{
            return redirect()->back()->with('errors', 'Ya existe esa Bebida');
        }
    }

    public function getBebida(Request $request)
    {
        $bebida = DB::table('products')
            ->join('product_contents', 'product_contents.product_id', '=', 'products.id')
            ->where('products.id', '=', $request->id)
            ->select('products.*')
            ->get();
        // dd($bebida);
        return $bebida;
    }

    public function updateBebida(Request $request)
    {
        $bebida = Product::where('id', '=', $request->modal_update_id)->first();

        if(!is_null($bebida)){

            $slug = DB::table('products')
                ->where('id', '<>', $request->modal_update_id)
                ->where('slug', '=', $request->modal_update_slug)
                ->first();

            if(!$slug){
                if($request->hasFile('modal_update_image')){
                    $file = dirname(base_path(), 1).'/public_html/'.$bebida->image;
                        File::delete($file);
                        $imageName = $request->modal_update_slug.'.'.$request->modal_update_image->getClientOriginalExtension();
                        $route = 'backend/img/bebidas/'.$imageName;

                        $bebida->name = $request->modal_update_name;
                        $bebida->slug = $request->modal_update_slug;
                        $bebida->image = $route;
                        $bebida->subcategory_id = $request->modal_update_subcategory_id;
                        $bebida->status = $request->modal_update_status;
                        $bebida->description = $request->modal_update_description;
                        $bebida->update();

                        $request->modal_update_image->move(dirname(base_path(), 1).'/public_html/backend/img/bebidas/',$imageName);

                        $contenido = ProductContent::where('product_id', $bebida->id)->first();

                        $contenido->price = $request->modal_update_price;
                        $contenido->update();

                    return redirect()->back()->with('success', 'Bebida Actualizada Correctamente');
                }
                else{
                    $bebida->name = $request->modal_update_name;
                    $bebida->slug = $request->modal_update_slug;
                    $bebida->subcategory_id = $request->modal_update_subcategory_id;
                    $bebida->description = $request->modal_update_description;
                    $bebida->status = $request->modal_update_status;
                    $bebida->update();

                    $contenido = ProductContent::where('product_id', $bebida->id)->first();

                    $contenido->price = $request->modal_update_price;
                    $contenido->update();

                    return redirect()->back()->with('success', 'Bebida Actualizada Correctamente');
                }

            }
            else{
                return redirect()->back()->with('errors', 'Ya existe esa Bebida');
            }

        }
        else{
            return redirect()->back()->with('errors', 'No existe esa Bebida');
        }
    }

    public function deleteBebida(Request $request)
    {
        $logo = Product::where('id', $request->id)->select('image')->first();

        $image = dirname(base_path(), 1).'/public_html/'.$logo->image;


        File::delete($image);
        $bebida = Product::where('id', $request->id)->first();

        $bebida->delete();
    }
}

app/Http/Controllers/Backend/DashboardController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class DashboardController extends Controller
{
    public function dashboard()
    {
        return view('backend.admin.dashboard');
    }
}

app/Http/Controllers/Backend/OrderDetailsController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class OrderDetailsController extends Controller
{
    //
}

resources/views/backend/orders/index.blade.php
@extends('layouts.backend.main')

@section('title', 'Pedidos')

@section('custom-css')
    <!-- DataTables -->
    <link rel="stylesheet" href="{{ asset('backend/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css') }}">
    <link rel="stylesheet" href="{{ asset('backend/plugins/datatables-responsive/css/responsive.bootstrap4.min.css') }}">
    <!-- SweetAlert2 -->
    <link rel="stylesheet" href="{{ asset('backend/plugins/sweetalert2-theme-bootstrap-4/bootstrap-4.min.css') }}">
@endsection

@section('page-title', 'Listado de Pedidos')

@section('content')
    <div class="card">
        @if(session()->has('success'))
            <div class="row text-center">
                <div class="col-sm-3"></div>
                <div class="col-sm-6 text-center">
                    <div class="alert alert-success alert-dismissible fade show" role="alert">
                        <p class="text-white h5">{{ session()->get('success') }}</p>
                        <button type="button" class="close text-white" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                </div>
            </div>
        @elseif(session()->has('errors'))
            <div class="row text-center">
                <div class="col-sm-3"></div>
                <div class="col-sm-6 text-center">
                    <div class="alert alert-warning alert-dismissible fade show" role="alert">
                        <p class="text-white h5">{{ session()->get('errors') }}</p>
                        <button type="button" class="close text-white" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                </div>
            </div>
        @endif
        <!-- /.card-header -->
        <div class="card-body">
            <table id="tableOrders" class="table table-bordered">
                <thead class="text-center">
                    <tr>
                        <th>#</th>
                        <th>Cliente</th>
                        <th>Dirección</th>
                        <th>Tipo de Envío</th>
                        <th>Método de Pago</th>
                        <th>Total</th>
                        <th>Status</th>
                        <th>Fecha Compra</th>
                        <th>Acciones</th>
                    </tr>
                </thead>
                <tbody class="text-center">
                    @foreach ($orders as $order)
                        <tr id="{{ $order->id }}">
                            <td>{{ $order->id }}</td>
                            <td>{{ $order->customer }}</td>
                            <td class="text-left" style="width: 20%">
                              {{ $order->customer_address }}
                            </td>
                            <td>{{ $order->tipoEnvio }}</td>
                            <td>{{ $order->metodoPago }}</td>
                            <td>$ {{ $order->total }}</td>
                            <td style="width: 10%">
                                @if($order->status == 'recibido')
                                    <span class="badge bg-primary">ORDEN RECIBIDA</span>
                                @elseif($order->status == 'transaccion')
                                    <span class="badge bg-warning">ESPERANDO TRANSACCIÓN</span>
                                @elseif($order->status == "preparacion")
                                    <span class="bagde bg-info">EN PREPARACIÓN</span>
                                @elseif($order->status == "enviando")
                                    <span class="badge bg-secondary">ENVIANDO</span>
                                @elseif($order->status == "cancelado")
                                    <span class="badge bg-danger">CANCELADO</span>
                                @else
                                    <span class="badge bg-success">ENTREGADO AL CLIENTE</span>
                                @endif
                            </td>
                            <td>{{ $order->fechaCompra }}</td>
                            <td>
                                <button class="btn btn-md btn-danger btn-block" type="button" onclick="downloadPDF({{ $order->id }})">
                                    <i class="fas fa-file-pdf"></i>
                                    Descargar
                                </button>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
                <tfoot class="text-center">
                    <tr>
                        <th>#</th>
                        <th>Cliente</th>
                        <th>Dirección</th>
                        <th>Tipo de Envío</th>
                        <th>Método de Pago</th>
                        <th>Total</th>
                        <th>Status</th>
                        <th>Fecha Compra</th>
                        <th>Acciones</th>
                    </tr>
                </tfoot>
            </table>
        </div>
    </div>


@endsection

@section('custom-js')
    <script src="{{ asset('backend/plugins/datatables/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('backend/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js') }}"></script>
    <script src="{{ asset('backend/plugins/datatables-responsive/js/dataTables.responsive.min.js') }}"></script>
    <script src="{{ asset('backend/plugins/datatables-responsive/js/responsive.bootstrap4.min.js') }}"></script>
    {{-- bs-custom-file-input --}}
    <script src="{{ asset('backend/plugins/bs-custom-file-input/bs-custom-file-input.min.js') }}"></script>
    {{-- SweetAlert 2 --}}
    <script src="{{ asset('backend/plugins/sweetalert2/sweetalert2.min.js') }}"></script>

    <script type="text/javascript">
        $(function () {
            $('#tableOrders').DataTable({
                "paging": true,
                "lengthChange": true,
                "searching": true,
                "ordering": true,
                "info": true,
                "autoWidth": true,
                "responsive": true,
                "order": [[ 0, "desc" ]]
            });
        });

        function downloadPDF(order_id){
            $.ajax({
                url: '{{ route('admin.adminDownloadPDF') }}',
                method: 'POST',
                data: {
                    "_token": "{{ csrf_token() }}",
                    "order": order_id
                },
                xhrFields: {
                    responseType: 'blob'
                },
                success: function (data) {
                    var blob = new Blob([data]);
                    var link = document.createElement('a');
                    link.href = window.URL.createObjectURL(blob);
                    link.download = "Ticket de Compra #"+order_id+".pdf";
                    link.click();
                    // document.body.removeChild(link);
                },error: function(xhr, ajaxOptions, thrownError){
                    $('.loading').hide();
                    console.log(xhr.status+" ,"+" "+ajaxOptions+", "+thrownError);
                }
            }).done(function (response){

            });
        }

    </script>
@endsection